/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4luc3XTrqrw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import React from "react";

import Link from "next/link";
// import LocationOnIcon from "@mui/icons-material/LocationOn";
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";

import { Button } from "../ui/button";
import { Toggle } from "../ui/toggle";
import Modal from "react-modal";
import { useState , useEffect } from "react";
import GoogleMapsComponent from "../ui/GoogleMapsComponent";
import { AvatarImage, AvatarFallback, Avatar } from "../ui/avatar";
import { format } from "date-fns";
import {
  DropdownMenuTrigger,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu,
} from "../ui/dropdown-menu";
import { Label } from "../ui/label";
import { Input } from "../ui/input";
import {
  PopoverTrigger,
  PopoverContent,
  Popover,
} from "../ui/popover";
import { Calendar } from "../ui/calendar";
import { CalendarIcon } from "@radix-ui/react-icons";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "../ui/select";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "../ui/card";

export function Component() {
  const [modalIsOpen, setModalIsOpen] = useState(false);
  const [isModelContent,setIsModelContent] = useState(false);

  const openModal = (e) => {
    e.preventDefault(); // Prevent form submission
    setModalIsOpen(true);
  };

  const closeModal = () => {
    setModalIsOpen(false);
  };
  

  // const ModalContent = () => {
  //   // Content of your modal

  //   return (
  //     <div className="modal-content relative">
  //       <div className="map-container">
  //         <GoogleMapsComponent/>
  //       </div>
        
        
  //       <div className="absolute buttom-0 right-5">
  //         <Button className="bottom-0">Apply</Button>
  //       </div>
  //       <style jsx>{`
  //         .map-container {
  //           height: 550px;
  //         }
  //       `}</style>
  //     </div>
  //   );
  // };

  const ModalContent = () => {
    // Content of your modal
  
    const [mapKey, setMapKey] = useState(Date.now());
  
    useEffect(() => {
      // When the modal opens, generate a new key to remount the map component
      setMapKey(Date.now());
    }, [modalIsOpen]);
  
    return (
      <div className="modal-content relative">
        {modalIsOpen && (
          <div className="map-container">
            <GoogleMapsComponent key={mapKey} />
          </div>
        )}
        <div className="absolute buttom-0 right-5">
          <Button className="bottom-0">Apply</Button>
        </div>
        <style jsx>{`
          .map-container {
            height: 550px;
          }
        `}</style>
      </div>
    );
  };
  const [selectedDate, setSelectedDate] = useState(null);
  const [popoverOpen, setPopoverOpen] = useState(false); // State to manage popover visibility

  const handleDateSelect = (date: Date) => {
    setSelectedDate(date);
    setPopoverOpen(false); // Close the popover after selecting a date
  };

  const togglePopover = () => {
    setPopoverOpen(!popoverOpen);
  };
  return (
    <>
      <header className="bg-gray-900 text-white py-4 px-6 md:px-8 lg:px-10">
        <div className="flex items-center justify-between">
          <Link
            className="text-2xl font-bold"
            href="#"
            style={{ color: "#A7E92F" }}
          >
            .Busify
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="hover:text-gray-300" href="#">
              Home
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Historique
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Settings
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Button size="icon" variant="ghost">
              <BellIcon className="h-6 w-6" />
            </Button>
            <Toggle aria-label="Toggle dark mode">
              <MoonIcon className="h-6 w-6" />
            </Toggle>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Avatar className="h-8 w-8 cursor-pointer">
                  <AvatarImage src="https://github.com/shadcn.png" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem className="cursor-pointer">
                  <UserIcon className="mr-2 h-4 w-4" />
                  Edit Profile
                </DropdownMenuItem>
                <DropdownMenuItem className="text-red-600 cursor-pointer">
                  <LogOutIcon className="mr-2 h-4 w-4 text-red-600" />
                  <p className="text-red-600">Log Out</p>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>
      <main className="bg-gray-100 py-12 px-6 md:px-8 lg:px-10">
        <div className="container mx-auto">
          <div
            style={{
              backgroundImage:
                "linear-gradient(rgba(255, 255, 255, 0.7), rgba(255, 255, 255, 0.7)), url('https://img.freepik.com/free-vector/flat-polygonal-background_23-2148919305.jpg?w=826&t=st=1714900403~exp=1714901003~hmac=aca0f56a7bd17076ce6f50cba79a3e1907feb08285779afdc1c9fdb475d2babc')",
            }}
            className="bg-cover bg-no-repeat rounded-lg shadow-md p-8 md:p-12 lg:p-16 "
          >
            <h1 className="text-3xl font-bold mb-4">Book your Seat</h1>
            <p className="text-gray-600 mb-8">
              Search for bus tickets and plan your journey.
            </p>
            <form className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <Label htmlFor="destination">Destination</Label>
                <div className="w-full">
                  <Button
                    onClick={openModal}
                    className="bg-gray-100 text-black hover:bg-gray-200 w-full text-left flex justify-between"
                  >
                    Choose Destination
                    {/* < className="mr-2" /> */}
                  </Button>
                </div>

                {modalIsOpen &&
                <Modal
                  isOpen={modalIsOpen}
                  onRequestClose={closeModal}
                  contentLabel="Choose Destination Modal"
                >
                  
                  <ModalContent />
                </Modal>
              }
              </div>
              <div>
                <Label htmlFor="date">Travel Date</Label>
                <Popover open={popoverOpen} onOpenChange={setPopoverOpen}>
                  <PopoverTrigger asChild>
                    <Button
                      className="w-full flex items-center justify-between"
                      variant="outline"
                      onClick={togglePopover}
                    >
                      <span>
                        {selectedDate
                          ? format(selectedDate, "PPP")
                          : "Select date"}
                      </span>
                      <CalendarIcon className="w-5 h-5" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="p-0">
                    <Calendar mode="single" onSelect={handleDateSelect} />
                  </PopoverContent>
                </Popover>
              </div>
              <div>
                <Label htmlFor="time">Departure Time</Label>
                <Select>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select time" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="06:00">06:00 AM</SelectItem>
                    <SelectItem value="07:00">07:00 AM</SelectItem>
                    <SelectItem value="08:00">08:00 AM</SelectItem>
                    <SelectItem value="09:00">09:00 AM</SelectItem>
                    <SelectItem value="10:00">10:00 AM</SelectItem>
                    <SelectItem value="11:00">11:00 AM</SelectItem>
                    <SelectItem value="12:00">12:00 PM</SelectItem>
                    <SelectItem value="13:00">01:00 PM</SelectItem>
                    <SelectItem value="14:00">02:00 PM</SelectItem>
                    <SelectItem value="15:00">03:00 PM</SelectItem>
                    <SelectItem value="16:00">04:00 PM</SelectItem>
                    <SelectItem value="17:00">05:00 PM</SelectItem>
                    <SelectItem value="18:00">06:00 PM</SelectItem>
                    <SelectItem value="19:00">07:00 PM</SelectItem>
                    <SelectItem value="20:00">08:00 PM</SelectItem>
                    <SelectItem value="21:00">09:00 PM</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Button className="col-span-1 md:col-span-3" type="submit">
                Book now
              </Button>
            </form>
          </div>
        </div>
      </main>
      <section className="bg-white py-12 px-6 md:px-8 lg:px-10">
        <div className="container mx-auto">
          <h2 className="text-2xl font-bold mb-8">Available Bus Rides</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card
              style={{
                backgroundImage:
                  "linear-gradient(rgba(255, 255, 255, 0.9), rgba(255, 255, 255, 0.9)), url('https://img.freepik.com/free-vector/flat-polygonal-background_23-2148919305.jpg?w=826&t=st=1714900403~exp=1714901003~hmac=aca0f56a7bd17076ce6f50cba79a3e1907feb08285779afdc1c9fdb475d2babc')",
              }}
            >
              <CardHeader>
                <CardTitle>1337 Bus</CardTitle>
                <CardDescription>Departs at 8:00 AM</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex justify-between items-center mb-4">
                  <div>
                    <div className="text-lg font-bold">Free</div>
                    <div className="text-gray-600">One-way</div>
                  </div>
                  <div>
                    <div className="text-lg font-bold">3h 30m</div>
                    <div className="text-gray-600">Duration</div>
                  </div>
                </div>
                <div className="flex justify-between items-center">
                  <div>
                    <div className="text-lg font-bold">8:00 AM</div>
                    <div className="text-gray-600">Departure</div>
                  </div>
                  <div>
                    <div className="text-lg font-bold">11:30 AM</div>
                    <div className="text-gray-600">Arrival</div>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button>Select</Button>
              </CardFooter>
            </Card>
            <Card
              style={{
                backgroundImage:
                  "linear-gradient(rgba(255, 255, 255, 0.9), rgba(255, 255, 255, 0.9)), url('https://img.freepik.com/free-vector/flat-polygonal-background_23-2148919305.jpg?w=826&t=st=1714900403~exp=1714901003~hmac=aca0f56a7bd17076ce6f50cba79a3e1907feb08285779afdc1c9fdb475d2babc')",
              }}
            >
              <CardHeader>
                <CardTitle>1337 Bus</CardTitle>
                <CardDescription>Departs at 10:00 AM</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex justify-between items-center mb-4">
                  <div>
                    <div className="text-lg font-bold">Free</div>
                    <div className="text-gray-600">One-way</div>
                  </div>
                  <div>
                    <div className="text-lg font-bold">4h 15m</div>
                    <div className="text-gray-600">Duration</div>
                  </div>
                </div>
                <div className="flex justify-between items-center">
                  <div>
                    <div className="text-lg font-bold">10:00 AM</div>
                    <div className="text-gray-600">Departure</div>
                  </div>
                  <div>
                    <div className="text-lg font-bold">2:15 PM</div>
                    <div className="text-gray-600">Arrival</div>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button>Select</Button>
              </CardFooter>
            </Card>
            <Card
              style={{
                backgroundImage:
                  "linear-gradient(rgba(255, 255, 255, 0.9), rgba(255, 255, 255, 0.9)), url('https://img.freepik.com/free-vector/flat-polygonal-background_23-2148919305.jpg?w=826&t=st=1714900403~exp=1714901003~hmac=aca0f56a7bd17076ce6f50cba79a3e1907feb08285779afdc1c9fdb475d2babc')",
              }}
            >
              <CardHeader>
                <CardTitle>1337 Bus</CardTitle>
                <CardDescription>Departs at 12:00 PM</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex justify-between items-center mb-4">
                  <div>
                    <div className="text-lg font-bold">Free</div>
                    <div className="text-gray-600">One-way</div>
                  </div>
                  <div>
                    <div className="text-lg font-bold">3h 00m</div>
                    <div className="text-gray-600">Duration</div>
                  </div>
                </div>
                <div className="flex justify-between items-center">
                  <div>
                    <div className="text-lg font-bold">12:00 PM</div>
                    <div className="text-gray-600">Departure</div>
                  </div>
                  <div>
                    <div className="text-lg font-bold">3:00 PM</div>
                    <div className="text-gray-600">Arrival</div>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button>Select</Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </section>
      <footer className="bg-gray-900 text-white py-6 px-6 md:px-8 lg:px-10">
        <div className="container mx-auto flex items-center justify-between">
          <div>© 2024 BusBooking. All rights reserved.</div>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="hover:text-gray-300" href="#">
              Privacy Policy
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Terms of Service
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Contact Us
            </Link>
          </nav>
        </div>
      </footer>
    </>
  );
}

function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  );
}

function CalendarDaysIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  );
}

function LogOutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  );
}

function MoonIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  );
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
